# Generated by Django 6.0.5 on 2026-05-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benevole',
            name='email',
        ),
        migrations.AddField(
            model_name='benevole',
            name='telephone',
            field=models.CharField(default='Inconnu', max_length=20),
            preserve_default=False,
        ),
    ]
