# Generated by Django 6.0.5 on 2026-08-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_remove_benevole_email_benevole_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_mode', models.CharField(choices=[('NONE', 'Aucun'), ('NOEL', 'Noël'), ('HALLOWEEN', 'Halloween'), ('PAQUES', 'Pâques'), ('ETE', 'Été'), ('AUTOMNE', 'Automne'), ('RENTREE', 'Rentrée')], default='NONE', max_length=20)),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
    ]
